---
- name: EXTEND EPG TO VLAN
  hosts: apic
  connection: local
  gather_facts: false

  vars:
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      tenant_container:
        mgmt: "10.220.0.0/16"
        shg: "10.221.0.0/16"
        common: "10.229.0.0/16"
        ss_22: "10.221.0.0/16"
      aci_phys_dom:
        mgmt: "dom_phys_mgmt"
        shg: "dom_phys_sg"
        common: "dom_phys_common"

  tasks:
    - name: PROCESS EACH EPG
      include_tasks: includes/connect-epg-to-vlan.yml
      loop: "{{ epg_names }}"
      loop_control:
        loop_var: epg_name